<?php

/**
 * @file
 * Contains cke_div.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cke_div_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ckeditor_entity_link module.
    case 'help.page.cke_div':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allows to insert DIV tag in CKEditor.') . '</p>';
      return $output;

    default:
  }
}
